create table if not exists public.duel_challenges (
  duel_id text primary key,
  creator text not null,
  joiner text,
  stake numeric not null,
  session_pub_key text not null,
  status text not null default 'open',
  created_at timestamptz not null default timezone('utc', now()),
  updated_at timestamptz not null default timezone('utc', now())
);

create table if not exists public.duel_events (
  id bigint generated by default as identity primary key,
  duel_id text not null references public.duel_challenges(duel_id) on delete cascade,
  sender text not null,
  type text not null,
  payload jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default timezone('utc', now())
);

create index if not exists duel_challenges_status_created_idx
  on public.duel_challenges (status, created_at desc);

create index if not exists duel_events_duel_id_id_idx
  on public.duel_events (duel_id, id);
